<?php

namespace App;

use App\Traits\ImageAttributeTrait;
use App\Traits\ImageWithThumbResizeTrait;
use App\Traits\SortableModelTrait;
use Illuminate\Database\Eloquent\Model;

class HomePageInfoCard extends Model
{
	use ImageWithThumbResizeTrait;
	use ImageAttributeTrait;
	use SortableModelTrait;
	
	protected static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
		static::addGlobalScope(
			'ordered', function ($query) {
			$query->orderBy('sort_order');
		});
	}
	
	public function getImageAttribute($value)
	{
		return $this->getImage($value);
	}
	
	public function getImageThumbAttribute($value)
	{
		return $this->getImageThumb($value);
	}
	
	public function setImageAttribute($value)
	{
		if(app()->runningInConsole()){
			$this->attributes['image'] = $value;
			return;
		}
		$this->fitImageWithThumb('image', $value, 'home_page_info_cards', 360, 1, 215, NULL);
	}
}
