<?php

namespace App;

use App\Traits\SortableModelTrait;
use Illuminate\Database\Eloquent\Model;

class Navbar extends Model
{
	use SortableModelTrait;
	
	protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::addGlobalScope(
            'active',
            function ($query) {
                $query->where('is_active', true);
            });
    }
    
    public function parent()
	{
		return $this->belongsTo(Navbar::class, 'parent_id');
	}
	
	public function children()
	{
		return $this->hasMany(Navbar::class, 'parent_id');
	}
	
}
