<?php

namespace App;

use App\Traits\SortableModelTrait;
use Illuminate\Database\Eloquent\Model;

class SocialLink extends Model
{
	use SortableModelTrait;
	
	protected $guarded = [];
	
	protected static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
		static::addGlobalScope(
			'ordered', function ($query) {
			$query->orderBy('sort_order');
		});
	}
}
